- name: install libcap2-bin
  apt: pkg=libcap2-bin state=latest

- name: copy nflx-proxy
  copy: src=nflx-proxy
        dest=/usr/local/bin/nflx-proxy
        owner=root
        group=root
        mode=0755
  notify:
    - set capability
