- name: add golang repo
  apt_repository: repo='ppa:duh/golang'

- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - gdb
    - git
    - golang
    - make
    - mercurial
  environment:
    LANG: en_US.UTF-8
